### ISSUE TITLE
no attribute 'pipe_abort_read_r' on --replay

### ISSUE THREAD

**Issue by zed** [bessman/pytest-reserial#23]
```python
Traceback (most recent call last):
  ...
  File "/home/me/.venv/lib/python3.11/site-packages/custom_device/__init__.py", line 101, in _loop
    sync = self.ser.read(size=1)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/me/.venv/lib/python3.11/site-packages/serial/serialposix.py", line 565, in rea...
    ready, _, _ = select.select([self.fd, self.pipe_abort_read_r], [], [], timeout.time_left())
                                          ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Serial' object has no attribute 'pipe_abort_read_r'
```

```
pyserial==3.5
pytest-reserial==0.4.1
```

**Comment by bessman** [comment]
Thank you for the bug report!

The original `Serial.read` method has somehow leaked into the replay environment. I need more details to understand how it happened.

Can you share the test code, and the precise steps you take to run pytest?

**Comment by zed** [comment]
The code is rather involved (multiple threads, serial is called via 3rd party library). I've managed to make it work with PR #24.

**Comment by bessman** [comment]
Thank you!
